# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configurationwidget.ui'
#
# Created: Tue Sep 13 04:20:41 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ConfigurationWidget(object):
    def setupUi(self, ConfigurationWidget):
        ConfigurationWidget.setObjectName(_fromUtf8("ConfigurationWidget"))
        ConfigurationWidget.resize(363, 384)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConfigurationWidget.sizePolicy().hasHeightForWidth())
        ConfigurationWidget.setSizePolicy(sizePolicy)
        ConfigurationWidget.setMinimumSize(QtCore.QSize(350, 0))
        ConfigurationWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        ConfigurationWidget.setWindowTitle(QtGui.QApplication.translate("ConfigurationWidget", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        ConfigurationWidget.setTitle(QtGui.QApplication.translate("ConfigurationWidget", "Graph configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout = QtGui.QFormLayout(ConfigurationWidget)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(ConfigurationWidget)
        self.label.setText(QtGui.QApplication.translate("ConfigurationWidget", "Split:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.splitComboBox = QtGui.QComboBox(ConfigurationWidget)
        self.splitComboBox.setObjectName(_fromUtf8("splitComboBox"))
        self.splitComboBox.addItem(_fromUtf8(""))
        self.splitComboBox.setItemText(0, QtGui.QApplication.translate("ConfigurationWidget", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.splitComboBox.addItem(_fromUtf8(""))
        self.splitComboBox.setItemText(1, QtGui.QApplication.translate("ConfigurationWidget", "Authors", None, QtGui.QApplication.UnicodeUTF8))
        self.splitComboBox.addItem(_fromUtf8(""))
        self.splitComboBox.setItemText(2, QtGui.QApplication.translate("ConfigurationWidget", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.splitComboBox.addItem(_fromUtf8(""))
        self.splitComboBox.setItemText(3, QtGui.QApplication.translate("ConfigurationWidget", "Branches", None, QtGui.QApplication.UnicodeUTF8))
        self.splitComboBox.addItem(_fromUtf8(""))
        self.splitComboBox.setItemText(4, QtGui.QApplication.translate("ConfigurationWidget", "Directories", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.splitComboBox)
        self.label_2 = QtGui.QLabel(ConfigurationWidget)
        self.label_2.setText(QtGui.QApplication.translate("ConfigurationWidget", "Filename:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(ConfigurationWidget)
        self.label_3.setText(QtGui.QApplication.translate("ConfigurationWidget", "Image Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.imageTitleLineEdit = QtGui.QLineEdit(ConfigurationWidget)
        self.imageTitleLineEdit.setObjectName(_fromUtf8("imageTitleLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.imageTitleLineEdit)
        self.filenameLineEdit = QtGui.QLineEdit(ConfigurationWidget)
        self.filenameLineEdit.setObjectName(_fromUtf8("filenameLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.filenameLineEdit)
        self.label_4 = QtGui.QLabel(ConfigurationWidget)
        self.label_4.setText(QtGui.QApplication.translate("ConfigurationWidget", "Skip merges:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.skipMergesCheckBox = QtGui.QCheckBox(ConfigurationWidget)
        self.skipMergesCheckBox.setText(_fromUtf8(""))
        self.skipMergesCheckBox.setObjectName(_fromUtf8("skipMergesCheckBox"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.skipMergesCheckBox)
        self.label_5 = QtGui.QLabel(ConfigurationWidget)
        self.label_5.setText(QtGui.QApplication.translate("ConfigurationWidget", "Show tags:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.showTagsCheckBox = QtGui.QCheckBox(ConfigurationWidget)
        self.showTagsCheckBox.setText(_fromUtf8(""))
        self.showTagsCheckBox.setObjectName(_fromUtf8("showTagsCheckBox"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.showTagsCheckBox)
        self.maxcaptionSpinBox = QtGui.QSpinBox(ConfigurationWidget)
        self.maxcaptionSpinBox.setToolTip(QtGui.QApplication.translate("ConfigurationWidget", "Maximum number of captions (when using --split).", None, QtGui.QApplication.UnicodeUTF8))
        self.maxcaptionSpinBox.setSuffix(QtGui.QApplication.translate("ConfigurationWidget", " captions", None, QtGui.QApplication.UnicodeUTF8))
        self.maxcaptionSpinBox.setMinimum(1)
        self.maxcaptionSpinBox.setMaximum(30)
        self.maxcaptionSpinBox.setProperty("value", 4)
        self.maxcaptionSpinBox.setObjectName(_fromUtf8("maxcaptionSpinBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.maxcaptionSpinBox)
        self.maxcaptionsLabel = QtGui.QLabel(ConfigurationWidget)
        self.maxcaptionsLabel.setText(QtGui.QApplication.translate("ConfigurationWidget", "Max captions:", None, QtGui.QApplication.UnicodeUTF8))
        self.maxcaptionsLabel.setObjectName(_fromUtf8("maxcaptionsLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.maxcaptionsLabel)
        self.label_6 = QtGui.QLabel(ConfigurationWidget)
        self.label_6.setText(QtGui.QApplication.translate("ConfigurationWidget", "Use lines:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_6)
        self.uselinesCheckBox = QtGui.QCheckBox(ConfigurationWidget)
        self.uselinesCheckBox.setText(_fromUtf8(""))
        self.uselinesCheckBox.setObjectName(_fromUtf8("uselinesCheckBox"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.uselinesCheckBox)
        self.label_7 = QtGui.QLabel(ConfigurationWidget)
        self.label_7.setText(QtGui.QApplication.translate("ConfigurationWidget", "Time range:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_7)
        self.timerangeComboBox = QtGui.QComboBox(ConfigurationWidget)
        self.timerangeComboBox.setObjectName(_fromUtf8("timerangeComboBox"))
        self.timerangeComboBox.addItem(_fromUtf8(""))
        self.timerangeComboBox.setItemText(0, QtGui.QApplication.translate("ConfigurationWidget", "All available", None, QtGui.QApplication.UnicodeUTF8))
        self.timerangeComboBox.addItem(_fromUtf8(""))
        self.timerangeComboBox.setItemText(1, QtGui.QApplication.translate("ConfigurationWidget", "Last year", None, QtGui.QApplication.UnicodeUTF8))
        self.timerangeComboBox.addItem(_fromUtf8(""))
        self.timerangeComboBox.setItemText(2, QtGui.QApplication.translate("ConfigurationWidget", "Last month", None, QtGui.QApplication.UnicodeUTF8))
        self.timerangeComboBox.addItem(_fromUtf8(""))
        self.timerangeComboBox.setItemText(3, QtGui.QApplication.translate("ConfigurationWidget", "Last week", None, QtGui.QApplication.UnicodeUTF8))
        self.timerangeComboBox.addItem(_fromUtf8(""))
        self.timerangeComboBox.setItemText(4, QtGui.QApplication.translate("ConfigurationWidget", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.timerangeComboBox)
        self.label_8 = QtGui.QLabel(ConfigurationWidget)
        self.label_8.setText(QtGui.QApplication.translate("ConfigurationWidget", "Start date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(ConfigurationWidget)
        self.label_9.setText(QtGui.QApplication.translate("ConfigurationWidget", "End date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_9)
        self.startDateEdit = QtGui.QDateEdit(ConfigurationWidget)
        self.startDateEdit.setObjectName(_fromUtf8("startDateEdit"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.startDateEdit)
        self.endDateEdit = QtGui.QDateEdit(ConfigurationWidget)
        self.endDateEdit.setObjectName(_fromUtf8("endDateEdit"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.endDateEdit)

        self.retranslateUi(ConfigurationWidget)
        QtCore.QMetaObject.connectSlotsByName(ConfigurationWidget)

    def retranslateUi(self, ConfigurationWidget):
        pass

