#!/bin/bash
avr-gcc -o $1 -mmcu=atmega32 $1.c $2.c

if(($? !=0));
	then 
	  exit 1
fi

echo Compilatio Successful

objcopy -v -S -O ihex $1 $1.hex

avrdude -v -y -p atmega32 -P /dev/ttyS0 -c stk500v2 -U flash:w:$1.hex:i

avrdude -v -y -p atmega32 -P /dev/ttyS0 -c stk500v2 -U lfuse:w:0xE1:m


